version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/InsightDashboard.Pn/InsightDashboard.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/InsightDashboard.Pn/InsightDashboard.Pn.Test"
  schedule:
    interval: daily